project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
    path('katalog/', include('katalog.urls')),
    path('mywatchlist/', include('mywatchlist.urls')),
    path('todolist/', include('todolist.urls')),
]

# TODO: Implement Routings Here

todolist/urls.py
from django.urls import path
from todolist.views import show_todolist
from todolist.views import register
from todolist.views import login_user
from todolist.views import logout_user
from todolist.views import create_task
from todolist.views import delete
from todolist.views import ubah
from todolist.views import show_json
from todolist.views import create_task_ajax
from todolist.views import delete_ajax

app_name = 'todolist'

urlpatterns = [
    path('', show_todolist, name='show_todolist'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('create-task/', create_task, name='create_task'),
    path('delete/<int:id>', delete_ajax, name='delete_ajax'),
    path('ubah/<int:id>', ubah, name='ubah'),
    path('json/', show_json, name='show_json'),
    path('create-ajax/', create_task_ajax, name='create_task_ajax'),
]

urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

todolist/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Task(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateField()
    title = models.TextField()
    description = models.TextField()
    is_finished = models.BooleanField(default=False)

todolist/forms.py
from django import forms
from todolist.models import Task

class create_form(forms.Form):
    title = forms.CharField(label = "Title", max_length=255)
    description = forms.CharField(label = "Description")

todolist/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from todolist.models import Task
from django.shortcuts import redirect
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
import datetime
from django.http import HttpResponseRedirect
from django.urls import reverse
from .forms import create_form
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse
from django.http import HttpResponse
from django.core import serializers

# Create your views here.
def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Akun telah berhasil dibuat!')
            return redirect('todolist:login')
    
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user) # melakukan login terlebih dahulu
            response = HttpResponseRedirect(reverse("todolist:show_todolist")) # membuat response
            response.set_cookie('last_login', str(datetime.datetime.now())) # membuat cookie last_login dan menambahkannya ke dalam response
            return response
        else:
            messages.info(request, 'Username atau Password salah!')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('todolist:login'))
    response.delete_cookie('last_login')
    return response

@login_required(login_url='/todolist/login/')
def show_todolist(request):
    # data_task = Task.objects.filter(user = request.user) #sesuai sama user yang lagi login
    context = {
        # 'list_task': data_task,
        'last_login': request.COOKIES['last_login'],
    }
    return render(request, 'todolist.html', context)

def show_json(request):
    data_task = Task.objects.filter(user = request.user) #sesuai sama user yang lagi login
    return HttpResponse(serializers.serialize("json", data_task), content_type="application/json")

@login_required(login_url='/todolist/login/')
def create_task(request):
    if request.method == 'POST':
        title = request.POST.get('title')
        description = request.POST.get('description')
        if title != "" or description != "":
            Task.objects.create(title = title, description = description, date = datetime.datetime.now(), user = request.user)
            return redirect('todolist:show_todolist')
        else:
            messages.info(request, 'Isi informasi tugas dengan benar!')
    context = {}
    return render(request, 'create_task.html', context)

@login_required(login_url='/todolist/login/')
@csrf_exempt
def create_task_ajax(request):
    if request.method == 'POST':
        title = request.POST.get('title')
        description = request.POST.get('description')
        if title != "" or description != "":
            task = Task.objects.create(title = title, description = description, date = datetime.datetime.now(), user = request.user)
            context = {
                'pk' : task.pk,
                'fields' : {
                    'title' : task.title,
                    'description' : task.description,
                    'is_finished' : task.is_finished,
                    'date' : task.date
                }
            }
            return JsonResponse(context)

def delete(request, id):
  member = Task.objects.get(id=id)
  member.delete()
  return redirect('todolist:show_todolist')

@login_required(login_url='/todolist/login/')
@csrf_exempt
def delete_ajax(request, id):
    if (request.method == 'DELETE'):
        Task.objects.filter(id=id).delete()
        return HttpResponse(status=202)

def ubah(request, id):
  member = Task.objects.get(id=id)
  member.is_finished = not(member.is_finished)
  member.save()
  return redirect('todolist:show_todolist')

todolist/templates/create_task.html
{% extends 'base.html' %}

{% block meta %}
<title>Tambah Tugas</title>
{% endblock meta %}

{% block content %}
<nav class="navbar navbar-expand-lg shadow-md py-2 bg-purple relative flex items-center w-full justify-between">
  <div class="px-16 w-full flex justify-between">
    <h1 class = "text-xl font-bold text-white py-4">My Todolist</h1>
  </div>
</nav>  

<div class = "create_task px-16 flex justify-center">
    <div>
        <h1 class = "text-3xl font-bold text-purple py-4 content-center">Tambah Tugas</h1>  

            <form method="POST" >  
                {% csrf_token %}  
                <table>  
                    <tr>
                        <td>Title: </td>
                        <td><input type="text" name="title" placeholder="Title" class="form-control block w-full px-3 py-1.5 text-base font-normal text-gray-700 bg-white bg-clip-padding border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none"></td>
                    </tr>
                            
                    <tr>
                        <td>Description: </td>
                        <td><input type="text" name="description" placeholder="Description" class="form-control block w-full px-3 py-1.5 text-base font-normal text-gray-700 bg-white bg-clip-padding border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none"></td>
                    </tr>
                    <tr>  
                        <td></td>
                        <td><input button class = "bg-blue hover:bg-dark_blue text-white font-semibold hover:text-white py-2 px-4 border border-transparent hover:border-transparent rounded" type="submit" name="submit" value="Tambah"/></td>  
                    </tr>  
                </table>  
            </form>

        {% if messages %}  
            <ul>   
                {% for message in messages %}  
                    <li>{{ message }}</li>  
                    {% endfor %}  
            </ul>   
        {% endif %}
    </div>
</div>  

{% endblock content %}

todolist/templates/login.html
{% extends 'base.html' %}

{% block content %}
<nav class="navbar navbar-expand-lg shadow-md py-2 bg-purple relative flex items-center w-full justify-between">
  <div class="px-16 w-full flex justify-between">
    <h1 class = "text-xl font-bold text-white py-4">My Todolist</h1>
  </div>
</nav>

{% block meta %}
<title>Login</title>
{% endblock meta %}

<body class = "text-black">
    <div class = "login px-16 flex justify-center">
        <div>
            <h1 class = "text-3xl font-bold text-purple py-4 content-center">Log In</h1>

            <form method="POST" action="">
                {% csrf_token %}
                <table>
                    <tr>
                        <td>Username: </td>
                        <td><input type="text" name="username" placeholder="Username" class="form-control block w-full px-3 py-1.5 text-base font-normal text-gray-700 bg-white bg-clip-padding border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none"></td>
                    </tr>
                            
                    <tr>
                        <td>Password: </td>
                        <td><input type="password" name="password" placeholder="Password" class="form-control block w-full px-3 py-1.5 text-base font-normal text-gray-700 bg-white bg-clip-padding border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none"></td>
                    </tr>

                    <tr>
                        <td></td>
                        <td><input class="bg-blue hover:bg-dark_blue text-white font-semibold hover:text-white py-2 px-4 border border-transparent hover:border-transparent rounded" type="submit" value="Login"></td>
                    </tr>
                </table>
            </form>

            {% if messages %}
                <ul>
                    {% for message in messages %}
                        <li>{{ message }}</li>
                    {% endfor %}
                </ul>
            {% endif %}     
                
            Belum mempunyai akun? <a class = "text-purple underline" href="{% url 'todolist:register' %}">Buat Akun</a>
            </div>
    </div>
</body>
{% endblock content %}

{% comment %} {% extends 'base.html' %}

{% block meta %}
<title>Login</title>
{% endblock meta %}

{% block content %}

<body class = "text-black">
<div class = "login">

    <h1 class = "text-3xl font-bold text-purple">Login</h1>

    <form method="POST" action="">
        {% csrf_token %}
        <table>
            <tr>
                <td>Username: </td>
                <td><input type="text" name="username" placeholder="Username" class="form-control"></td>
            </tr>
                    
            <tr>
                <td>Password: </td>
                <td><input type="password" name="password" placeholder="Password" class="form-control"></td>
            </tr>

            <tr>
                <td></td>
                <td><input class="btn login_btn" type="submit" value="Login"></td>
            </tr>
        </table>
    </form>

    {% if messages %}
        <ul>
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}     
        
    Belum mempunyai akun? <a href="{% url 'todolist:register' %}">Buat Akun</a>

</div>

{% endblock content %} {% endcomment %}

todolist/templates/register.html
{% extends 'base.html' %}

{% block meta %}
<title>Registrasi Akun</title>
{% endblock meta %}

{% block content %}
<nav class="navbar navbar-expand-lg shadow-md py-2 bg-purple relative flex items-center w-full justify-between">
  <div class="px-16 w-full flex justify-between">
    <h1 class = "text-xl font-bold text-white py-4">My Todolist</h1>
  </div>
</nav> 

<div class = "login px-16 flex justify-center">
    <div>
        <h1 class = "text-3xl font-bold text-purple py-4 content-center">Formulir Registrasi</h1>  

            <form method="POST" >  
                {% csrf_token %} 
                {% for field in form %}
                    <p>
                        {{ field.label_tag }}<br>
                        {{ field }}
                        {% if field.help_text %}
                            <small style="color: grey">{{ field.help_text }}</small>
                        {% endif %}
                        {% for error in field.errors %}
                            <p style="color: red">{{ error }}</p>
                        {% endfor %}
                    </p>
              {% endfor %}
              <td><input class="bg-blue hover:bg-dark_blue text-white font-semibold hover:text-white py-2 px-4 border border-transparent hover:border-transparent rounded" type="submit" name="submit" value="Daftar"/></td>
            </form>

        Sudah mempunyai akun? <a class = "text-purple underline" href="{% url 'todolist:login' %}">Log In</a>
    </div>
</div>  

{% endblock content %}

todolist/templates/todolist.html
{% extends 'base.html' %}

{% block meta %}
<title>MyTodolist</title>
{% endblock meta %}

{% block content %}
<head>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
  <script>
    $(document).ready(function(){
      $.get( "/todolist/json/", function( data ) {
        for (let i = 0; i < data.length; i++) {
          $('#todolist').append(
            `<div id = "${data[i].pk}--tugas" class = "rounded-lg pl-10 pr-6 py-5 bg-white shadow-md hover:shadow-xl">
              <div>
                <h1 class = "font-semibold text-grey text-sm">${data[i].fields.date}</h1>
                <h1 class = "text-lg font-bold">${data[i].fields.title}</h1>
                <p class="text-gray-700 text-base mb-4">
                  ${data[i].fields.description}
                </p>
              </div>
      
              <div class="flex justify-between">
                ${data[i].fields.is_finished ?
                  `<span class = "text-sm sm:text-md bg-green text-white py-2 px-3 sm: px-3 rounded-full">Selesai</span>` :
                  `<span class = "text-sm sm:text-md bg-red text-white py-2 px-3 sm: px-3 rounded-full">Belum Selesai</span>`}      
                <div>
                  ${data[i].fields.is_finished ?
                  `<td><button class = "text-sm sm:text-md bg-blue hover:bg-dark_blue text-white font-semibold hover:text-white py-2 px-3 border border-transparent hover:border-transparent rounded"><a href="/todolist/ubah/${data[i].pk}"><i class="bi bi-x-circle-fill"></i></a></button></td>` :
                  `<td><button class = "text-sm sm:text-md bg-blue hover:bg-dark_blue text-white font-semibold hover:text-white py-2 px-3 border border-transparent hover:border-transparent rounded"><a href="/todolist/ubah/${data[i].pk}"><i class="bi bi-check-circle-fill"></i></a></button></td>`}
                  <td><button class="text-sm sm:text-md bg-transparent hover:bg-light_blue text-blue font-semibold hover:text-blue py-2 px-3 border border-blue hover:border-blue rounded" onclick="hapusTugas(${data[i].pk})"><i class="bi bi-trash-fill"></i></button></td>
                </div>
              </div>
            </div>`
          );
        }
      });

      $("#tambah").click(function(){
        $.post( "/todolist/create-ajax/", {title : $("#title").val(), description : $("#description").val()}, function(data, status) {
          if (status == "success") {
            $('#todolist').append(
            `<div id = "${data.pk}--tugas" class = "rounded-lg pl-10 pr-6 py-5 bg-white shadow-md hover:shadow-xl">
              <div>
                <h1 class = "font-semibold text-grey text-sm">${data.fields.date}</h1>
                <h1 class = "text-lg font-bold">${data.fields.title}</h1>
                <p class="text-gray-700 text-base mb-4">
                  ${data.fields.description}
                </p>
              </div>
      
              <div class="flex justify-between">
                ${data.fields.is_finished ?
                  `<span class = "text-sm sm:text-md bg-green text-white py-2 px-3 sm: px-3 rounded-full">Selesai</span>` :
                  `<span class = "text-sm sm:text-md bg-red text-white py-2 px-3 sm: px-3 rounded-full">Belum Selesai</span>`}      
                  <div>
                    ${data.fields.is_finished ?
                    `<td><button class = "text-sm sm:text-md bg-blue hover:bg-dark_blue text-white font-semibold hover:text-white py-2 px-3 border border-transparent hover:border-transparent rounded"><a href="/todolist/ubah/${data.pk}"><i class="bi bi-x-circle-fill"></i></a></button></td>` :
                    `<td><button class = "text-sm sm:text-md bg-blue hover:bg-dark_blue text-white font-semibold hover:text-white py-2 px-3 border border-transparent hover:border-transparent rounded"><a href="/todolist/ubah/${data.pk}"><i class="bi bi-check-circle-fill"></i></a></button></td>`}
                    <td><button class="text-sm sm:text-md bg-transparent hover:bg-light_blue text-blue font-semibold hover:text-blue py-2 px-3 border border-blue hover:border-blue rounded" onclick="hapusTugas(${data.pk})"><i class="bi bi-trash-fill"></i></button></td>
                  </div>
              </div>
            </div>`
            )
            $('#title').val('')
            $('#description').val('')
          }
        })
      })

      hapusTugas = (idTugas) => {
        $.ajax({
          url: `/todolist/delete/${idTugas}`,
          type: 'DELETE',
          success: function(response){
            $(`#${idTugas}--tugas`).remove()
          }
        })
      }
    });
  </script>
</head>
<nav class="navbar navbar-expand-lg shadow-md py-2 bg-purple relative flex items-center w-full justify-between">
  <div class="px-4 w-full flex justify-between sm:px-8 md:px-16">
    <h1 class = "text-md sm:text-xl font-bold text-white py-4">My Todolist</h1>
    <div class = "flex justify-end m-2 grid grid-cols-2 gap-2">
      <button class = "text-sm sm:text-md bg-blue hover:bg-dark_blue text-white font-semibold hover:text-white py-2 px-4 border border-transparent hover:border-transparent rounded" data-bs-toggle="modal" data-bs-target="#modalTambah"><i class="bi bi-plus-circle-fill"></i>  Tugas</button>
      <button class = "text-sm sm:text-md bg-transparent hover:bg-white text-white hover:text-purple font-semibold hover:white py-2 px-4 border border-white hover:border-transparent rounded"><a href="{% url 'todolist:logout' %}">Logout</a></button>
    </div>
  </div>
</nav>
<body class = "text-black">
  <div class = "px-4 sm:px-8 md:px-16">
    <h5 class = "text-3xl font-bold text-black py-4">Halo, {{user.get_username}}!</h5>
    <div class = "grid md:grid-cols-2 lg:grid-cols-3 w-full gap-5 mt-8 sm:mt-5" id = "todolist">
  </div>

  <!-- Modal -->
  <div class="modal fade" id="modalTambah" tabindex="-1" role="dialog" aria-labelledby="createTaskModalLabel" aria-hidden="true">
    <div class="modal-dialog bg-white rounded-md" role="document">
      <div class="modal-content bg-white rounded-md">
        <div class="modal-header rounded-md">
          <h5 class="modal-title text-black font-bold" id="createTaskModalLabel">Add Task</h5>
        </div>
        <div class="modal-body">
          {% csrf_token %}
          <table>  
            <tr>
                <td>Title: </td>
                <td><input type="text" id="title" name="title" placeholder="Title" class="form-control block w-full px-3 py-1.5 text-base font-normal text-gray-700 bg-white bg-clip-padding border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none"></td>
            </tr>
                    
            <tr>
                <td>Description: </td>
                <td><input type="text" id="description" name="description" placeholder="Description" class="form-control block w-full px-3 py-1.5 text-base font-normal text-gray-700 bg-white bg-clip-padding border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none"></td>
            </tr>
          </table>
        </div>
        <div class="modal-footer">
          <button type="button" class="text-sm sm:text-md bg-transparent hover:bg-light_blue text-blue font-semibold hover:text-blue py-2 px-3 border border-blue hover:border-blue rounded" data-bs-dismiss="modal">Cancel</button>
          <button id="tambah" type="button" class = "text-sm sm:text-md bg-blue hover:bg-dark_blue text-white font-semibold hover:text-white py-2 px-4 border border-transparent hover:border-transparent rounded" data-bs-dismiss="modal">Tambah</button>
        </div>
      </div>
    </div>
  </div>
</body>
<br>
<h5 class = "flex justify-center border-b">Sesi Terakhir Log In: {{ last_login }}</h5>
{% endblock content %}